.github/workflows/publish.yml
Signed-off-by: Clemens Grabmann <clemens.grabmann@cloudflight.io>
=> update release tag filter to prevent releases with a version typo

src/test/fixtures/java/single-java-module-constraints/build.gradle, src/test/fixtures/java/single-java-module-constraints/settings.gradle, src/test/fixtures/java/single-java-module-constraints/src/main/java/io/cloudflight/gradle/Foo.java, src/test/fixtures/java/single-java-module-constraints/src/test/java/io/cloudflight/gradle/FooTest.java, src/test/fixtures/kotlin/single-kotlin-module-constraints/build.gradle, src/test/fixtures/kotlin/single-kotlin-module-constraints/settings.gradle, src/test/fixtures/kotlin/single-kotlin-module-constraints/src/main/kotlin/io/cloudflight/gradle/Foo.kt, src/test/fixtures/kotlin/single-kotlin-module-server/build.gradle, src/test/fixtures/kotlin/single-kotlin-module-server/settings.gradle, src/test/fixtures/kotlin/single-kotlin-module-server/src/main/kotlin/io/cloudflight/gradle/Foo.kt, src/test/kotlin/io/cloudflight/gradle/autoconfigure/java/JavaConfigurePluginTest.kt, src/test/kotlin/io/cloudflight/gradle/autoconfigure/kotlin/KotlinConfigurePluginTest.kt
this PR adds a couple more scenarios with dependency constraints and the spring boot plugin that should be covered
=> add additional tests with constraints and spring boot plugin

src/main/kotlin/io/cloudflight/gradle/autoconfigure/kotlin/KotlinConfigurePlugin.kt
to work around bug in KotlinPlugin
=> #31 set `kotlin.jvmToolchain.languageVersion` explicitly

README.md, gradle.properties, gradle/libs.versions.toml, src/test/fixtures/node/single-ts-module/package-lock.json, src/test/fixtures/skeletons/kotlin-springboot-angular/skeleton-ui/package-lock.json, src/test/kotlin/io/cloudflight/gradle/autoconfigure/kotlin/KotlinConfigurePluginTest.kt
update to kotlin 1.7.10
update to spring boot 2.7.1
update to node-plugin 3.4.0
=> update gradle plugins

gradle.properties, src/main/kotlin/io/cloudflight/gradle/autoconfigure/kotlin/KotlinConfigurePlugin.kt
add the kotlin-bom instead of one certain module in order to ensure c…orrect dependency resolution
=> add the kotlin-bom 

README.md, src/main/kotlin/io/cloudflight/gradle/autoconfigure/java/JavaConfigurePlugin.kt, src/main/kotlin/io/cloudflight/gradle/autoconfigure/java/JavaConfigurePluginExtension.kt, src/main/kotlin/io/cloudflight/gradle/autoconfigure/kotlin/KotlinConfigurePlugin.kt, src/main/kotlin/io/cloudflight/gradle/autoconfigure/node/NodeConfigurePlugin.kt, src/test/fixtures/java/single-java-module-library-no-sources/build.gradle, src/test/fixtures/java/single-java-module-library-no-sources/settings.gradle, src/test/fixtures/java/single-java-module-library-no-sources/src/main/java/io/cloudflight/gradle/Foo.java, src/test/fixtures/java/single-java-module-library-no-sources/src/test/java/io/cloudflight/gradle/FooTest.java, src/test/kotlin/io/cloudflight/gradle/autoconfigure/java/JavaConfigurePluginTest.kt, src/test/kotlin/io/cloudflight/gradle/autoconfigure/node/NodeConfigurePluginTest.kt
=> [#71] add property to better configure if source artefacts are created

README.md, src/main/kotlin/io/cloudflight/gradle/autoconfigure/java/JavaConfigurePlugin.kt, src/test/fixtures/java/single-java-module-testfixtures/build.gradle, src/test/fixtures/java/single-java-module-testfixtures/settings.gradle, src/test/fixtures/java/single-java-module-testfixtures/src/main/java/io/cloudflight/gradle/Foo.java, src/test/fixtures/java/single-java-module-testfixtures/src/test/java/io/cloudflight/gradle/FooTest.java, src/test/fixtures/java/single-java-module-testfixtures/src/testFixtures/java/io/cloudflight/gradle/Person.java, src/test/kotlin/io/cloudflight/gradle/autoconfigure/java/JavaConfigurePluginTest.kt
=> #79 auto-apply the test-fixture plugin if src/testFixtures exist

README.md, src/main/kotlin/io/cloudflight/gradle/autoconfigure/java/JavaConfigurePluginExtension.kt
=> improved documentation

README.md, src/main/kotlin/io/cloudflight/gradle/autoconfigure/AutoConfigureGradlePlugin.kt, src/test/fixtures/autoconfigure/multi-module/kotlin-module/build.gradle, src/test/kotlin/io/cloudflight/gradle/autoconfigure/AutoconfigureGradlePluginTest.kt, src/test/kotlin/io/cloudflight/gradle/autoconfigure/java/JavaConfigurePluginTest.kt, src/test/kotlin/io/cloudflight/gradle/autoconfigure/kotlin/KotlinConfigurePluginTest.kt, src/test/kotlin/io/cloudflight/gradle/autoconfigure/node/NodeConfigurePluginTest.kt, src/test/kotlin/io/cloudflight/gradle/autoconfigure/report/ReportConfigurePluginTest.kt, src/test/kotlin/io/cloudflight/gradle/autoconfigure/swagger/SwaggerConfigurePluginTest.kt, src/test/kotlin/io/cloudflight/gradle/autoconfigure/test/util/ProjectFixture.kt
Solves only version propagation part of the related ticket
=> #76: propagate the root project version and group to all subprojects

README.md, src/main/kotlin/io/cloudflight/gradle/autoconfigure/swagger/SwaggerCodegenConfigurePlugin.kt, src/main/kotlin/io/cloudflight/gradle/autoconfigure/swagger/SwaggerCodegenConfigurePluginExtension.kt, src/test/fixtures/swagger/generate-swagger-from-file/petstore-client-node-overwrite/build.gradle, src/test/fixtures/swagger/generate-swagger-from-file/petstore-client-node-overwrite/package-lock.json, src/test/fixtures/swagger/generate-swagger-from-file/petstore-client-node-overwrite/package.json, src/test/fixtures/swagger/generate-swagger-from-file/petstore-client-node-overwrite/tsconfig.json, src/test/fixtures/swagger/generate-swagger-from-file/settings.gradle, src/test/kotlin/io/cloudflight/gradle/autoconfigure/swagger/SwaggerConfigurePluginTest.kt
Signed-off-by: Kangrui Ye <kangrui.ye@cloudflight.io>
=> #91: allow to specify custom generator for node projects

gradle/libs.versions.toml, src/main/kotlin/io/cloudflight/gradle/autoconfigure/node/Defaults.kt, src/main/kotlin/io/cloudflight/gradle/autoconfigure/node/NodeConfigurePlugin.kt, src/test/fixtures/node/single-ts-module/package-lock.json
=> #97 update to Node 18

src/main/kotlin/io/cloudflight/gradle/autoconfigure/AutoConfigureGradlePlugin.kt, src/test/kotlin/io/cloudflight/gradle/autoconfigure/AutoConfigureSettingsPluginTest.kt, src/test/kotlin/io/cloudflight/gradle/autoconfigure/AutoconfigureGradlePluginTest.kt, src/test/kotlin/io/cloudflight/gradle/autoconfigure/test/util/ProjectFixture.kt
=> #101 add a task to print the version number

README.md, src/main/kotlin/io/cloudflight/gradle/autoconfigure/AutoConfigureSettingsPlugin.kt
=> set the defaultInferredScope to patch in the reckon plugin

.github/workflows/build.yml, .github/workflows/publish.yml, README.md, build.gradle.kts, gradle.properties, settings.gradle.kts
=> use the reckon plugin for semantic versioning

build.gradle.kts, gradle/libs.versions.toml, src/main/kotlin/io/cloudflight/gradle/autoconfigure/AutoConfigureGradlePlugin.kt, src/main/kotlin/io/cloudflight/gradle/autoconfigure/util/BuildUtils.kt, src/main/kotlin/io/cloudflight/gradle/autoconfigure/util/EnvironmentUtils.kt, src/test/kotlin/io/cloudflight/gradle/autoconfigure/java/JavaConfigurePluginTest.kt, src/test/kotlin/io/cloudflight/gradle/autoconfigure/node/NodeConfigurePluginTest.kt, src/test/kotlin/io/cloudflight/gradle/autoconfigure/test/util/ProjectFixture.kt
=> using ci-info to detect CI environment

src/main/kotlin/io/cloudflight/gradle/autoconfigure/kotlin/KotlinConfigurePlugin.kt
=> #105 remove freeCompilerArgs assignment

README.md, settings.gradle.kts
=> update plugin version

build.gradle.kts, gradle/libs.versions.toml
=> remove kotlin-logging from the classpath

gradle/libs.versions.toml
=> update license-gradle-plugin to 1.2.0

README.md, src/main/kotlin/io/cloudflight/gradle/autoconfigure/AutoConfigureSettingsPlugin.kt, src/test/kotlin/io/cloudflight/gradle/autoconfigure/AutoConfigureSettingsPluginTest.kt
=> #112 only apply the Reckon-Plugin on CI environments

README.md, gradle/libs.versions.toml, src/main/kotlin/io/cloudflight/gradle/autoconfigure/kotlin/KotlinConfigurePlugin.kt, src/test/kotlin/io/cloudflight/gradle/autoconfigure/kotlin/KotlinConfigurePluginTest.kt
=> #118 update to Kotlin 1.7.21

src/main/kotlin/io/cloudflight/gradle/autoconfigure/AutoConfigureSettingsPlugin.kt, src/test/kotlin/io/cloudflight/gradle/autoconfigure/AutoConfigureSettingsPluginTest.kt
=> #116 only calculate the local development version once for all projects

gradle/libs.versions.toml
=> update license plugin to 1.2.1

gradle/libs.versions.toml
=> update to the license plugin 1.2.2

gradle/libs.versions.toml
=> #129 update license gradle plugin

src/main/kotlin/io/cloudflight/gradle/autoconfigure/AutoConfigureSettingsPlugin.kt, src/test/fixtures/autoconfigure-settings/single-java-module-reckon-override/settings.gradle, src/test/kotlin/io/cloudflight/gradle/autoconfigure/AutoConfigureSettingsPluginTest.kt
=> #132 applying the reckon plugin also locally, but overriding the reckoned version

README.md, gradle/libs.versions.toml, src/test/kotlin/io/cloudflight/gradle/autoconfigure/kotlin/KotlinConfigurePluginTest.kt
=> #140 update to Kotlin 1.8.0

.github/workflows/publish.yml, README.md, build.gradle.kts, gradle/libs.versions.toml, settings.gradle.kts, src/main/kotlin/io/cloudflight/gradle/autoconfigure/kotlin/KotlinConfigurePlugin.kt
=> #138 update to the Spring Boot 3 plugin

samples/kotlin-springboot-angular-settings/skeleton-ui/package-lock.json, samples/kotlin-springboot-angular/skeleton-ui/package-lock.json, src/main/kotlin/io/cloudflight/gradle/autoconfigure/java/JavaConfigurePlugin.kt, src/main/kotlin/io/cloudflight/gradle/autoconfigure/java/JavaConfigurePluginExtension.kt, src/test/fixtures/java/single-java-module-application/build.gradle, src/test/fixtures/kotlin/single-kotlin-module-server/build.gradle
=> major: apply the spring boot (and git) plugin locally (#143)

src/main/kotlin/io/cloudflight/gradle/autoconfigure/java/JavaConfigurePlugin.kt, src/test/fixtures/java/single-java-module-constraints/build.gradle, src/test/fixtures/kotlin/single-kotlin-module-constraints/build.gradle, src/test/fixtures/kotlin/single-kotlin-module-server/build.gradle
=> major: apply the JavaPlugin instead of the JavaLibraryPlugin (#127)

settings.gradle.kts, src/main/kotlin/io/cloudflight/gradle/autoconfigure/java/IsJavaProject.kt, src/main/kotlin/io/cloudflight/gradle/autoconfigure/kotlin/IsKotlinProject.kt, src/test/fixtures/autoconfigure/single-java-module-with-kotlin-fixtures/build.gradle, src/test/fixtures/autoconfigure/single-java-module-with-kotlin-fixtures/settings.gradle, src/test/fixtures/autoconfigure/single-java-module-with-kotlin-fixtures/src/main/java/io/cloudflight/gradle/Foo.java, src/test/fixtures/autoconfigure/single-java-module-with-kotlin-fixtures/src/test/java/io/cloudflight/gradle/FooTest.java, src/test/fixtures/autoconfigure/single-java-module-with-kotlin-fixtures/src/testFixtures/kotlin/io/cloudflight/gradle/FooFixture.kt, src/test/kotlin/io/cloudflight/gradle/autoconfigure/AutoconfigureGradlePluginTest.kt
* do the same for java
fixes #126
=> minor: (#126) recognize kotlin directory in all source sets and configure kotlin if found
